// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtnBr40CcnKyB2MQ7jYR0CDuulor3VBkQ',
    appId: '1:667708005091:web:d70701bf3e0f980eb6c3d6',
    messagingSenderId: '667708005091',
    projectId: 'exam-2de73',
    authDomain: 'exam-2de73.firebaseapp.com',
    storageBucket: 'exam-2de73.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo3OMPiXjUTpV9MbWJOUvy_OxWB3EbAk8',
    appId: '1:667708005091:android:175a12f767aec4a4b6c3d6',
    messagingSenderId: '667708005091',
    projectId: 'exam-2de73',
    storageBucket: 'exam-2de73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaOAPF4Y_Ji-OT4oFGS5J8u0UIbwnJPbU',
    appId: '1:667708005091:ios:aeace9b421804de4b6c3d6',
    messagingSenderId: '667708005091',
    projectId: 'exam-2de73',
    storageBucket: 'exam-2de73.firebasestorage.app',
    iosBundleId: 'com.example.xamAp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaOAPF4Y_Ji-OT4oFGS5J8u0UIbwnJPbU',
    appId: '1:667708005091:ios:aeace9b421804de4b6c3d6',
    messagingSenderId: '667708005091',
    projectId: 'exam-2de73',
    storageBucket: 'exam-2de73.firebasestorage.app',
    iosBundleId: 'com.example.xamAp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtnBr40CcnKyB2MQ7jYR0CDuulor3VBkQ',
    appId: '1:667708005091:web:5132c83fdcf5ef21b6c3d6',
    messagingSenderId: '667708005091',
    projectId: 'exam-2de73',
    authDomain: 'exam-2de73.firebaseapp.com',
    storageBucket: 'exam-2de73.firebasestorage.app',
  );
}
